apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: libdetect.kuhn.host
spec:
  secretName: libdetect-tls
  commonName: libdetect.kuhn.host
  dnsNames:
    - libdetect.kuhn.host
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
